/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaperId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const QuestionPaper = IDL.Record({
  'id' : PaperId,
  'subject' : IDL.Text,
  'year' : IDL.Text,
  'uploadTimestamp' : Timestamp,
  'midType' : IDL.Text,
  'storageRef' : ExternalBlob,
});
export const PaperFilter = IDL.Record({
  'subject' : IDL.Opt(IDL.Text),
  'year' : IDL.Opt(IDL.Text),
  'midType' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addMidType' : IDL.Func([IDL.Text], [], []),
  'addSubject' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePaper' : IDL.Func([PaperId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaper' : IDL.Func([PaperId], [IDL.Opt(QuestionPaper)], ['query']),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMidTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listPapers' : IDL.Func([PaperFilter], [IDL.Vec(QuestionPaper)], ['query']),
  'listSubjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'removeMidType' : IDL.Func([IDL.Text], [], []),
  'removeSubject' : IDL.Func([IDL.Text], [], []),
  'trackVisit' : IDL.Func([], [IDL.Nat], []),
  'uploadPaper' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [PaperId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaperId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const QuestionPaper = IDL.Record({
    'id' : PaperId,
    'subject' : IDL.Text,
    'year' : IDL.Text,
    'uploadTimestamp' : Timestamp,
    'midType' : IDL.Text,
    'storageRef' : ExternalBlob,
  });
  const PaperFilter = IDL.Record({
    'subject' : IDL.Opt(IDL.Text),
    'year' : IDL.Opt(IDL.Text),
    'midType' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addMidType' : IDL.Func([IDL.Text], [], []),
    'addSubject' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePaper' : IDL.Func([PaperId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaper' : IDL.Func([PaperId], [IDL.Opt(QuestionPaper)], ['query']),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMidTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listPapers' : IDL.Func([PaperFilter], [IDL.Vec(QuestionPaper)], ['query']),
    'listSubjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'removeMidType' : IDL.Func([IDL.Text], [], []),
    'removeSubject' : IDL.Func([IDL.Text], [], []),
    'trackVisit' : IDL.Func([], [IDL.Nat], []),
    'uploadPaper' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [PaperId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };