/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PaperFilter {
  'subject' : [] | [string],
  'year' : [] | [string],
  'midType' : [] | [string],
}
export type PaperId = bigint;
export interface QuestionPaper {
  'id' : PaperId,
  'subject' : string,
  'year' : string,
  'uploadTimestamp' : Timestamp,
  'midType' : string,
  'storageRef' : ExternalBlob,
}
export interface SiteNote { 'content' : string, 'updatedAt' : Timestamp }
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addMidType' : ActorMethod<[string], undefined>,
  'addSubject' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearNote' : ActorMethod<[], undefined>,
  'deletePaper' : ActorMethod<[PaperId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNote' : ActorMethod<[], [] | [SiteNote]>,
  'getPaper' : ActorMethod<[PaperId], [] | [QuestionPaper]>,
  'getVisitorCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMidTypes' : ActorMethod<[], Array<string>>,
  'listPapers' : ActorMethod<[PaperFilter], Array<QuestionPaper>>,
  'listSubjects' : ActorMethod<[], Array<string>>,
  'removeMidType' : ActorMethod<[string], undefined>,
  'removeSubject' : ActorMethod<[string], undefined>,
  'setNote' : ActorMethod<[string], undefined>,
  'trackVisit' : ActorMethod<[], bigint>,
  'uploadPaper' : ActorMethod<[string, string, string, ExternalBlob], PaperId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];