/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const AdminMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'imageRef' : IDL.Opt(IDL.Text),
});
export const PublicMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaperId = IDL.Nat;
export const SiteNote = IDL.Record({
  'content' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const QuestionPaper = IDL.Record({
  'id' : PaperId,
  'subject' : IDL.Text,
  'year' : IDL.Text,
  'uploadTimestamp' : Timestamp,
  'midType' : IDL.Text,
  'storageRef' : ExternalBlob,
});
export const PaperFilter = IDL.Record({
  'subject' : IDL.Opt(IDL.Text),
  'year' : IDL.Opt(IDL.Text),
  'midType' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAdminMessage' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [AdminMessage],
      [],
    ),
  'addLike' : IDL.Func([], [IDL.Nat], []),
  'addMidType' : IDL.Func([IDL.Text], [], []),
  'addPublicMessage' : IDL.Func([IDL.Text, IDL.Text], [PublicMessage], []),
  'addSubject' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearNote' : IDL.Func([], [], []),
  'deleteAdminMessage' : IDL.Func([IDL.Nat], [], []),
  'deletePaper' : IDL.Func([PaperId], [IDL.Bool], []),
  'deletePublicMessage' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLikeCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getNote' : IDL.Func([], [IDL.Opt(SiteNote)], ['query']),
  'getPaper' : IDL.Func([PaperId], [IDL.Opt(QuestionPaper)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdminMessages' : IDL.Func([], [IDL.Vec(AdminMessage)], ['query']),
  'listMidTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listPapers' : IDL.Func([PaperFilter], [IDL.Vec(QuestionPaper)], ['query']),
  'listPublicMessages' : IDL.Func([], [IDL.Vec(PublicMessage)], ['query']),
  'listSubjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'removeMidType' : IDL.Func([IDL.Text], [], []),
  'removeSubject' : IDL.Func([IDL.Text], [], []),
  'setNote' : IDL.Func([IDL.Text], [], []),
  'updateAdminMessage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'uploadPaper' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [PaperId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const AdminMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'imageRef' : IDL.Opt(IDL.Text),
  });
  const PublicMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaperId = IDL.Nat;
  const SiteNote = IDL.Record({
    'content' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const QuestionPaper = IDL.Record({
    'id' : PaperId,
    'subject' : IDL.Text,
    'year' : IDL.Text,
    'uploadTimestamp' : Timestamp,
    'midType' : IDL.Text,
    'storageRef' : ExternalBlob,
  });
  const PaperFilter = IDL.Record({
    'subject' : IDL.Opt(IDL.Text),
    'year' : IDL.Opt(IDL.Text),
    'midType' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAdminMessage' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [AdminMessage],
        [],
      ),
    'addLike' : IDL.Func([], [IDL.Nat], []),
    'addMidType' : IDL.Func([IDL.Text], [], []),
    'addPublicMessage' : IDL.Func([IDL.Text, IDL.Text], [PublicMessage], []),
    'addSubject' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearNote' : IDL.Func([], [], []),
    'deleteAdminMessage' : IDL.Func([IDL.Nat], [], []),
    'deletePaper' : IDL.Func([PaperId], [IDL.Bool], []),
    'deletePublicMessage' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLikeCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getNote' : IDL.Func([], [IDL.Opt(SiteNote)], ['query']),
    'getPaper' : IDL.Func([PaperId], [IDL.Opt(QuestionPaper)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdminMessages' : IDL.Func([], [IDL.Vec(AdminMessage)], ['query']),
    'listMidTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listPapers' : IDL.Func([PaperFilter], [IDL.Vec(QuestionPaper)], ['query']),
    'listPublicMessages' : IDL.Func([], [IDL.Vec(PublicMessage)], ['query']),
    'listSubjects' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'removeMidType' : IDL.Func([IDL.Text], [], []),
    'removeSubject' : IDL.Func([IDL.Text], [], []),
    'setNote' : IDL.Func([IDL.Text], [], []),
    'updateAdminMessage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'uploadPaper' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [PaperId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };